[supervisord]
nodaemon=true

[program:pypowsybl-mcp]
command=python %(ENV_MCP_HOME)s/pypowsybl_mcp/server.py
stdout_logfile=%(ENV_LOG_DIR)s/pypowsybl-mcp.log
redirect_stderr=true
autostart=true
autorestart=true
